name: Build GodModeToggle SDK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Download project
        uses: actions/checkout@v4

      - name: Create ScriptHookV import library
        shell: cmd
        run: lib /def:ScriptHookV.def /machine:x64 /out:ScriptHookV.lib

      - name: Configure
        run: cmake -S . -B build -A x64

      - name: Build
        run: cmake --build build --config Release

      - name: Upload GodModeToggle
        uses: actions/upload-artifact@v4
        with:
          name: GodModeToggle-SDK
          path: build/Release/GodModeToggle.asi
